### ISSUE TITLE
Feature Request: Add headers to CSV for local players import

### ISSUE THREAD

**Issue by VeeArr** [RedEther-Me/mtg-vue#19]
When importing local players into WER, you are required to specify the headers of each column each time players are imported. Alternatively, if the first row of the data has the names of the columns, this step can be skipped. Add headers to exported local players information to make importing players easier.

**Comment by ajohnson-ventera** [comment]
I'm aware of the ability to use headers, unfortunately, WER doesn't actually care about the headers.
